# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card.ui'
#
# Created: Thu May 08 14:34:56 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(750, 657)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_qrcode = QtGui.QFrame(self.centralwidget)
        self.frame_qrcode.setGeometry(QtCore.QRect(-10, 0, 411, 371))
        self.frame_qrcode.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_qrcode.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_qrcode.setObjectName(_fromUtf8("frame_qrcode"))
        self.gridLayout = QtGui.QGridLayout(self.frame_qrcode)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 130, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(160, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 130, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_image = QtGui.QLabel(self.frame_qrcode)
        self.label_image.setMinimumSize(QtCore.QSize(320, 320))
        self.label_image.setText(_fromUtf8(""))
        self.label_image.setObjectName(_fromUtf8("label_image"))
        self.gridLayout.addWidget(self.label_image, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(160, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 2, 1, 1)
        self.frame_param = QtGui.QFrame(self.centralwidget)
        self.frame_param.setGeometry(QtCore.QRect(404, 0, 341, 371))
        self.frame_param.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_param.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_param.setObjectName(_fromUtf8("frame_param"))
        self.groupBox = QtGui.QGroupBox(self.frame_param)
        self.groupBox.setGeometry(QtCore.QRect(50, 10, 211, 61))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.comboBox_level = QtGui.QComboBox(self.groupBox)
        self.comboBox_level.setGeometry(QtCore.QRect(50, 20, 121, 22))
        self.comboBox_level.setObjectName(_fromUtf8("comboBox_level"))
        self.comboBox_level.addItem(_fromUtf8(""))
        self.comboBox_level.addItem(_fromUtf8(""))
        self.comboBox_level.addItem(_fromUtf8(""))
        self.comboBox_level.addItem(_fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.frame_param)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 90, 211, 61))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.comboBox_size = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_size.setGeometry(QtCore.QRect(50, 20, 121, 22))
        self.comboBox_size.setMaxVisibleItems(20)
        self.comboBox_size.setObjectName(_fromUtf8("comboBox_size"))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.comboBox_size.addItem(_fromUtf8(""))
        self.groupBox_3 = QtGui.QGroupBox(self.frame_param)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 281, 91))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lineEdit_path = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_path.setGeometry(QtCore.QRect(20, 60, 171, 20))
        self.lineEdit_path.setObjectName(_fromUtf8("lineEdit_path"))
        self.checkBox_isSave = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_isSave.setGeometry(QtCore.QRect(20, 30, 251, 16))
        self.checkBox_isSave.setChecked(False)
        self.checkBox_isSave.setObjectName(_fromUtf8("checkBox_isSave"))
        self.pushButton_openDialog = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_openDialog.setGeometry(QtCore.QRect(210, 60, 61, 23))
        self.pushButton_openDialog.setObjectName(_fromUtf8("pushButton_openDialog"))
        self.groupBox_4 = QtGui.QGroupBox(self.frame_param)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 280, 241, 61))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pushButton_make = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_make.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton_make.setObjectName(_fromUtf8("pushButton_make"))
        self.pushButton_save = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_save.setGeometry(QtCore.QRect(160, 20, 75, 23))
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(400, 370, 341, 261))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox_5 = QtGui.QGroupBox(self.frame)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 20, 311, 241))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_logo = QtGui.QLabel(self.groupBox_5)
        self.label_logo.setGeometry(QtCore.QRect(20, 110, 100, 100))
        self.label_logo.setMinimumSize(QtCore.QSize(100, 100))
        self.label_logo.setText(_fromUtf8(""))
        self.label_logo.setObjectName(_fromUtf8("label_logo"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 291, 81))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.lineEdit_logoPath = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_logoPath.setGeometry(QtCore.QRect(10, 50, 191, 20))
        self.lineEdit_logoPath.setObjectName(_fromUtf8("lineEdit_logoPath"))
        self.pushButton_openLogo = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_openLogo.setGeometry(QtCore.QRect(210, 50, 75, 23))
        self.pushButton_openLogo.setObjectName(_fromUtf8("pushButton_openLogo"))
        self.checkBox_isLogo = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_isLogo.setGeometry(QtCore.QRect(20, 20, 71, 16))
        self.checkBox_isLogo.setChecked(False)
        self.checkBox_isLogo.setObjectName(_fromUtf8("checkBox_isLogo"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 370, 401, 261))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame_vcard = QtGui.QFrame(self.tab)
        self.frame_vcard.setGeometry(QtCore.QRect(10, 0, 371, 231))
        self.frame_vcard.setAutoFillBackground(True)
        self.frame_vcard.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_vcard.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_vcard.setObjectName(_fromUtf8("frame_vcard"))
        self.formLayout = QtGui.QFormLayout(self.frame_vcard)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.frame_vcard)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_name = QtGui.QLineEdit(self.frame_vcard)
        self.lineEdit_name.setText(_fromUtf8(""))
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEdit_name)
        self.label_3 = QtGui.QLabel(self.frame_vcard)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_mobilephone = QtGui.QLineEdit(self.frame_vcard)
        self.lineEdit_mobilephone.setObjectName(_fromUtf8("lineEdit_mobilephone"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_mobilephone)
        self.label_4 = QtGui.QLabel(self.frame_vcard)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_workphone = QtGui.QLineEdit(self.frame_vcard)
        self.lineEdit_workphone.setObjectName(_fromUtf8("lineEdit_workphone"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_workphone)
        self.label_5 = QtGui.QLabel(self.frame_vcard)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_email = QtGui.QLineEdit(self.frame_vcard)
        self.lineEdit_email.setObjectName(_fromUtf8("lineEdit_email"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_email)
        self.label_6 = QtGui.QLabel(self.frame_vcard)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_address = QtGui.QLineEdit(self.frame_vcard)
        self.lineEdit_address.setObjectName(_fromUtf8("lineEdit_address"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_address)
        self.label_7 = QtGui.QLabel(self.frame_vcard)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.textEdit_comment = QtGui.QTextEdit(self.frame_vcard)
        self.textEdit_comment.setObjectName(_fromUtf8("textEdit_comment"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.textEdit_comment)
        self.lineEdit_mobilephone2 = QtGui.QLineEdit(self.frame_vcard)
        self.lineEdit_mobilephone2.setObjectName(_fromUtf8("lineEdit_mobilephone2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_mobilephone2)
        self.label = QtGui.QLabel(self.frame_vcard)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_new = QtGui.QAction(MainWindow)
        self.action_new.setObjectName(_fromUtf8("action_new"))
        self.action_save = QtGui.QAction(MainWindow)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setObjectName(_fromUtf8("action_open"))

        self.retranslateUi(MainWindow)
        self.comboBox_level.setCurrentIndex(1)
        self.comboBox_size.setCurrentIndex(9)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "VCard", None))
        self.groupBox.setTitle(_translate("MainWindow", "容错率(纠错率)", None))
        self.comboBox_level.setProperty("currentText", _translate("MainWindow", "正常", None))
        self.comboBox_level.setItemText(0, _translate("MainWindow", "较低", None))
        self.comboBox_level.setItemText(1, _translate("MainWindow", "正常", None))
        self.comboBox_level.setItemText(2, _translate("MainWindow", "较高", None))
        self.comboBox_level.setItemText(3, _translate("MainWindow", "极高", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "单个Box尺寸(不影响屏幕显示)", None))
        self.comboBox_size.setItemText(0, _translate("MainWindow", "1", None))
        self.comboBox_size.setItemText(1, _translate("MainWindow", "2", None))
        self.comboBox_size.setItemText(2, _translate("MainWindow", "3", None))
        self.comboBox_size.setItemText(3, _translate("MainWindow", "4", None))
        self.comboBox_size.setItemText(4, _translate("MainWindow", "5", None))
        self.comboBox_size.setItemText(5, _translate("MainWindow", "6", None))
        self.comboBox_size.setItemText(6, _translate("MainWindow", "7", None))
        self.comboBox_size.setItemText(7, _translate("MainWindow", "8", None))
        self.comboBox_size.setItemText(8, _translate("MainWindow", "9", None))
        self.comboBox_size.setItemText(9, _translate("MainWindow", "10", None))
        self.comboBox_size.setItemText(10, _translate("MainWindow", "11", None))
        self.comboBox_size.setItemText(11, _translate("MainWindow", "12", None))
        self.comboBox_size.setItemText(12, _translate("MainWindow", "13", None))
        self.comboBox_size.setItemText(13, _translate("MainWindow", "14", None))
        self.comboBox_size.setItemText(14, _translate("MainWindow", "15", None))
        self.comboBox_size.setItemText(15, _translate("MainWindow", "16", None))
        self.comboBox_size.setItemText(16, _translate("MainWindow", "17", None))
        self.comboBox_size.setItemText(17, _translate("MainWindow", "18", None))
        self.comboBox_size.setItemText(18, _translate("MainWindow", "19", None))
        self.comboBox_size.setItemText(19, _translate("MainWindow", "20", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "输出二维码名片", None))
        self.checkBox_isSave.setText(_translate("MainWindow", "每次生成二维码名片均保存到本地", None))
        self.pushButton_openDialog.setText(_translate("MainWindow", "打开...", None))
        self.pushButton_make.setText(_translate("MainWindow", "生成", None))
        self.pushButton_save.setText(_translate("MainWindow", "保存", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "设置Logo", None))
        self.pushButton_openLogo.setText(_translate("MainWindow", "打开Logo", None))
        self.checkBox_isLogo.setText(_translate("MainWindow", "使用Logo", None))
        self.label_2.setText(_translate("MainWindow", "姓名：", None))
        self.label_3.setText(_translate("MainWindow", "手机：", None))
        self.label_4.setText(_translate("MainWindow", "工作电话：", None))
        self.label_5.setText(_translate("MainWindow", "电子邮箱", None))
        self.label_6.setText(_translate("MainWindow", "地址", None))
        self.label_7.setText(_translate("MainWindow", "备注", None))
        self.label.setText(_translate("MainWindow", "手机：", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "名片", None))
        self.action_new.setText(_translate("MainWindow", "新建", None))
        self.action_new.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.action_save.setText(_translate("MainWindow", "保存", None))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.action_open.setText(_translate("MainWindow", "打开", None))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O", None))

